@extends('main.about.base')

@section('styles')
<link rel="stylesheet" href="/assets/css/sidebar.css">
<link rel="stylesheet" href="/assets/css/terms.css">
<link href='https://fonts.googleapis.com/css?family=Raleway:400,300,500,600,700' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Lato:400,100,300,700,900italic' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="/assets/css/health.css">
@endsection

@section('content.inner')
@include('main.terms.header')
@include('main.partials.sidebar')

<div class="about-container">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<p class="title">
					Fueled by passion for Care and Wellness
				</p>
				<p class="subtitle">
					Finding care shouldn't feel like rocket science.
				</p>
				<p class="fancy"><span>Terms</span></p>
			</div>
		</div>
	</div>
</div>

<div class="content">
	<div class="container">
		<div class="row">
			<div class="col-md-12 terms-col">
				<h1 class="text-center"><strong>Terms of Service</strong></h1>
				<h2 class="text-center"><strong>Community Guidelines</strong></h2>

				<p class="term-content"><a href="/">CareParrot</a> is a free fun way to share your health experiences through videos and pic sharing with your friends and providers and to the world around you. You can manage your healthcare policies, get free quotes, create local CareCrew's dedicated to staying healthy, get free information on healthcare needs, and monitor your health journey with badges and rewards. Remember sharing is caring!</p>
				<p class="term-content">These Terms do indeed form a legally binding contract between you and CareParrot. So please read them carefully. By using the Services, you agree to the Terms. Of course, if you don't agree with them, then don't use the Services.</p>
				<p class="term-content">When you use these services (and any others we make available to you) you’ll inevitably share some information with us. We get that that can affect your privacy. So we want to be upfront about the information we collect, how we use it, whom we share it with, and the choices we give you to control, access, and update your information.</p>
				<h4 class="subheader">Information We Collect from Third Parties</h4>
				<p class="term-content">We may collect information that other users provide about you when they use our services. For example, if another user allows us to collect information from their device's contact list (and you’re one of that user’s contacts) we may combine the information we collect from that user’s contact list with other information we have collected about you. We may also obtain information from other companies that are owned or operated by us, or any other third-party sources, and combine that with the information we collect through our services.</p>
				<h2 class="text-center">How We Share Information</h2>
				<h4 class="subheader">We may share information about you in the following ways:</h4>
				<p class="term-content">With other CareParrotters</p>
				<p class="term-content">We may share the following information with other CareParrotters: </p>
				<p class="term-content">information about you, such as your username and name;</p>
				<p class="term-content">information about how you have interacted with the services, such as your CareParrot “score,” the names of CareParrotters you are friends with, and other information that will help CareParrotters understand your connections with others using the services. For example, because it may not be clear whether a new friend request comes from someone you actually know, we may share whether you and the requestor have CareParrot friends in common; any additional information you have consented for us to share. For example, when you let us access your device phonebook, we may share information about you with other users who have your phone number in their device phonebook; and content you post or send will be shared with other CareParrotters; how widely your content is shared depends on your personal settings and the type of service you are using. </p>
				<h4 class="subheader">With all CareParrotters and the general public</h4>
				<p class="term-content">We may share the following information with all CareParrotters as well as the general public: public information like your CareParrot profile address and profile pictures; and any content that you submit to public venues. If a public venue is streamed on the web or broadcast in some other media, it may be viewed by the public at large.</p>
				<h4 class="subheader">With our affiliates</h4>
				<p class="term-content">We may share information with entities within the CareParrot family of companies.</p>
				<h4 class="subheader">With third parties</h4>
				<p class="term-content">We may share your information with the following third parties: </p>
				<h4 class="subheader">With service providers, sellers, and partners</h4>
				<p class="term-content">We may share information about you with service providers who perform services on our behalf, sellers that provide goods through our services, and business partners that provide services and functionality.</p>
				<h4 class="subheader">With third parties for legal reasons</h4>
				<p class="term-content">We may share information about you if we reasonably believe that disclosing the information is needed to:  comply with any valid legal process, government request, or applicable law, rule, or regulation, investigate, remedy, or enforce potential Terms of Service violations, protect the rights, property, and safety of us, our users, or others, or detect and resolve any fraud or security concerns.</p>
				<h4 class="subheader">Information You Choose to Share with Third Parties</h4>
				<p class="term-content">The services may also contain third-party links and search results, include third-party integrations, or be a co-branded or third-party-branded service that’s being provided jointly with or by another company. By going to those links, using the third-party integration, or using a co-branded or third-party-branded service, you may be providing information (including personal information) directly to the third party, us, or both. You acknowledge and agree that we are not responsible for how those third parties collect or use your information. As always, we encourage you to review the privacy policies of every third-party website or service that you visit or use, including those third parties you interact with through our services. Any approved third-party partner service will appear in our <a href="/careconnect" target="_blank">CareConnect</a>. These third parties are required to adhere to a confidentiality policy between our two parties.</p>
				<h4 class="subheader">How Long We Keep Your Content</h4>
				<p class="term-content">There are various ways CareParrotters can save content and also upload it to CareParrot (like as an attachment in Chat). We go into more detail below about how users can save CareParrot content. Your content will be stored as long as your remain as a CareParrot member and up to 180 days after deletion. Your content will be deactivated (which means it cannot be seen) within 30 days of deleting an account. Any important policies or records however will be kept permanently until provider or records transfer request with a deletion of records request is put in with CareParrot. Even then, if any applicable law requires us to keep this information on file for extended period of time, we will be under regulation to comply. You should understand that users who see the content you provide can always save it using any number of techniques: screenshots, in-app functionality, or any other image-capture technology. It’s also possible, as with any digital information, that someone might be able to access messages forensically or find them in a device’s temporary storage. Keep in mind that, while our systems are designed to carry out our deletion practices, we cannot promise that deletion will occur within a specific timeframe. And we may also retain certain information in backup for a limited period of time or as required by law.</p>
				<h4 class="subheader">Access and Updates</h4>
				<p class="term-content">We strive to let you access and update most of the personal information that we have about you. There are limits though to the requests we’ll accommodate. We may reject a request for a number of reasons, including, for example, that the request risks the privacy of other users, requires technical efforts that are disproportionate to the request, is repetitive, or is unlawful. You can access and update most of your basic account information right in the app by visiting the app’s Settings page. If you need to access, update, or delete any other personal information that we may have, see our HIPAA policy. We will try to update and access your information for free, but if it would require a disproportionate effort on our part, we may charge a fee. We will of course disclose the fee before we comply with your request. </p>
				<h4 class="subheader">Revoking Permissions</h4>
				<p class="term-content">If you change your mind about our ongoing ability to collect information from certain sources that you have already consented to, such as your phonebook, camera, photos, or location services, you can simply revoke your consent by changing the settings on your device if your device offers those options. Of course, if you do that, certain services may lose full functionality.</p>
				<h4 class="subheader">Account Deletion</h4>
				<p class="term-content">While we hope you’ll remain a lifelong CareParrotter, if for some reason you ever want to delete your account, you will have up to 30 days to restore your account before we delete your information from our servers. During this period of time, your account will be considered inactive and will not be visible to other CareParrotters. We will not however delete any healthcare records or medical records or docs you may have stored on our servers. These records will become deactivated and stored, if in case you decide later that you'd like to access them, or have them transferred to another EMR company or Healthcare Provider.</p>
				<h4 class="subheader">Communicating with other CareParrotters</h4>
				<p class="term-content">It’s also important to us that you stay in control over whom you communicate with. That’s why we’ve built a number of tools in Settings that let you indicate, among other things, who you want to see your Profile from just your friends or all CareParrotters, and whether you’d like to block another CareParrotter from contacting you again. </p>
				<h4 class="subheader">Users Outside the United States</h4>
				<p class="term-content">Although we welcome CareParrotters from all over the world, keep in mind that no matter where you live or where you happen to use our services, we operate our services from the United States. This means that we may collect your personal information from, transfer it to, and store and process it in the United States and other countries whose local data-protection and privacy laws may offer fewer protections than those in your country of residence or from any country where you use or access the services.</p>
				<h4 class="subheader">Children</h4>
				<p class="term-content">Our services are not intended for anyone under 13. And that’s why we do not knowingly collect personal information from anyone under 13.</p>
				<h4 class="subheader">Anti - Abuse Policy</h4>
				<p class="term-content">Our community is growing every day and we strive to welcome people to an environment free from abusive content. To do this, we rely on people like you. If you see something on CareParrot that you believe violates our terms, please report it. We have dedicated teams working around the world to review things you report to help make sure CareParrot remains safe. </p>
				<p class="term-content">Governments also sometimes ask us to remove content that violates local laws, but does not violate our Community Standards. If after careful legal review, we find that the content is illegal under local law, then we may make it unavailable only in the relevant country or territory. </p>
				<p class="term-content">Please keep the following in mind: </p>
				<p class="term-content">We may take action any time something violates the Community Standards. Reporting something doesn't guarantee that it will be removed because it may not violate our policies. </p>
				<p class="term-content">Our content reviewers will look to you for information about why a post may violate our policies. If you report content, please tell us why the content should be removed so that we can send it to the right person for review. </p>
				<p class="term-content">Our review decisions may occasionally change after receiving additional context about specific posts or after seeing new, violating content appearing on a Page or CareParrot Profile. The number of reports does not impact whether something will be removed. We never remove content simply because it has been reported a number of times. The consequences for violating our Community Standards vary depending on the severity of the violation and the person's history on CareParrot. For instance, we may warn someone for a first violation, but if we continue to see further violations we may restrict a person's ability to post on CareParrot or ban the person from CareParrot.</p>
				<p class="term-content">Not all disagreeable or disturbing content violates our Community Standards. For this reason, we offer you the ability to customize and control what you see by blocking, and hiding the posts, people, Pages, and applications you don’t want to see – and we encourage you to use these controls to better personalize your experience. People also often resolve issues they have about a piece of content by simply reaching out to the person who posted it. We’ve created tools for you to communicate directly with other people when you’re unhappy with posts, photos, or other content you see on CareParrot. </p>
				<h4 class="subheader text-center">Safety Policies</h4>
				<p class="term-content">We carefully review reports of threatening language to identify serious threats of harm to public and personal safety. We remove credible threats of physical harm to individuals. We also remove specific threats of theft, vandalism, or other financial harm. We may consider things like a person's physical location or public visibility in determining whether a threat is credible. We may assume credibility of any threats to people living in violent and unstable regions. We don’t allow the promotion of self-injury or suicide. We work with organizations to provide assistance for people in distress. We prohibit content that promotes or encourages suicide or any other type of self-injury, including self-mutilation and eating disorders. We don't consider body modification to be self-injury. We also remove any content that identifies victims or survivors of self-injury or suicide and targets them for attack, either seriously or humorously. People can, however, share information about self-injury and suicide that does not promote these things. We don’t allow any organizations that are engaged in the following to have a presence on CareParrot: terrorist activity, or organized criminal activity. </p>
				<p class="term-content">We also remove content that expresses support for groups that are involved in the violent or criminal behavior mentioned above. Supporting or praising leaders of those same organizations, or condoning their violent activities, is not allowed. </p>
				<p class="term-content">We welcome broad discussion and social commentary on these general subjects, but ask that people show sensitivity towards victims of violence and discrimination. We don’t tolerate bullying or harassment. We allow you to speak freely on matters and people of public interest, but remove content that appears to purposefully target private individuals with the intention of degrading or shaming them. This content includes, but is not limited to: Pages that identify and shame private individuals, images altered to degrade private individuals, photos or videos of physical bullying posted to shame the victim, sharing personal information to blackmail or harass people, and repeatedly targeting other people with unwanted friend requests or messages.</p>
				<p class="term-content">We define private individuals as people who have neither gained news attention nor the interest of the public, by way of their actions or public profession. </p>
				<p class="term-content">We permit open and critical discussion of people who are featured in the news or have a large public audience based on their profession or chosen activities. We remove credible threats to public figures, as well as hate speech directed at them – just as we do for private individuals.</p>
				<p class="term-content">We prohibit the use of CareParrot to facilitate or organize criminal activity that causes physical harm to people, businesses or animals, or financial damage to people or businesses. We work with law enforcement when we believe there is a genuine risk of physical harm or direct threats to public safety. </p>
				<p class="term-content">We also prohibit you from celebrating any crimes you’ve committed. We do, however, allow people to debate or advocate for the legality of criminal activities, as well as address them in a humorous or satirical way.</p>
				<p class="term-content">We remove content that threatens or promotes sexual violence or exploitation. This includes the sexual exploitation of minors, and sexual assault. To protect victims and survivors, we also remove photographs or videos depicting incidents of sexual violence and images shared in revenge or without permissions from the people in the images. </p>
				<p class="term-content">Our definition of sexual exploitation includes solicitation of sexual material, any sexual content involving minors, threats to share intimate images, and offers of sexual services. Where appropriate, we refer this content to law enforcement. Offers of sexual services include prostitution, escort services, sexual massages, and filmed sexual activity.</p>
				<p class="term-content">We prohibit any attempts by private individuals to purchase, sell, or trade prescription drugs, marijuana, firearms or ammunition. If you post an offer to purchase or sell alcohol, tobacco, or adult products, we expect you to comply with all applicable laws and carefully consider the audience for that content. We do not allow you to use CareParrot's payment tools to sell or purchase regulated goods on our platform.</p>
				<p class="term-content">People sometimes share content containing nudity for reasons like awareness campaigns or artistic projects. We restrict the display of nudity because some audiences within our global community may be sensitive to this type of content - particularly because of their cultural background or age. In order to treat people fairly and respond to reports quickly, it is essential that we have policies in place that our global teams can apply uniformly and easily when reviewing content. As a result, our policies can sometimes be more blunt than we would like and restrict content shared for legitimate purposes. We are always working to get better at evaluating this content and enforcing our standards. </p>
				<p class="term-content">We remove photographs of people displaying genitals or focusing in on fully exposed buttocks. We also restrict some images of female breasts if they include the nipple, but we always allow photos of women actively engaged in breastfeeding or showing breasts with post-mastectomy scarring. We also allow photographs of paintings, sculptures, and other art that depicts nude figures. Restrictions on the display of both nudity and sexual activity also apply to digitally created content unless the content is posted for educational, humorous, or satirical purposes. Explicit images of sexual intercourse are prohibited. Descriptions of sexual acts that go into vivid detail may also be removed. </p>
				<p class="term-content">CareParrot removes hate speech, which includes content that directly attacks people based on their: race, ethnicity, national origin, religious affiliation, sexual orientation, sex, gender, or gender identity, or serious disabilities or diseases. Organizations and people dedicated to promoting hatred against these protected groups are not allowed a presence on CareParrot. As with all of our standards, we rely on our community to report this content to us. </p>
				<p class="term-content">People can use CareParrot to challenge ideas, institutions, and practices. Such discussion can promote debate and greater understanding. Sometimes people share content containing someone else's hate speech for the purpose of raising awareness or educating others about that hate speech. When this is the case, we expect people to clearly indicate their purpose, which helps us better understand why they shared that content. </p>
				<p class="term-content">We allow humor, satire, or social commentary related to these topics, and we believe that when people use their authentic identity, they are more responsible when they share this kind of commentary. For that reason, we ask that Page owners associate their name and CareParrot Profile with any content that is insensitive, even if that content does not violate our policies. As always, we urge people to be conscious of their audience when sharing this type of content. </p>
				<p class="term-content">While we work hard to remove hate speech, we also give you tools to avoid distasteful or offensive content. You can also use CareParrot to speak up and educate the community around you. Counter-speech in the form of accurate information and alternative viewpoints can help create a safer and more respectful environment.</p>
				<p class="term-content">Violence and Graphic Content</p>
				<p class="term-content">CareParrot is a place where people share their experiences and raise awareness about important issues. Sometimes, those experiences and issues involve violence and graphic images of public interest or concern, such as human rights abuses or acts of terrorism. In many instances, when people share this type of content, they are condemning it or raising awareness about it. We remove graphic images when they are shared for sadistic pleasure or to celebrate or glorify violence. </p>
				<p class="term-content">When people share anything on CareParrot, we expect that they will share it responsibly, including carefully choosing who will see that content. We also ask that people warn their audience about what they are about to see if it includes graphic violence. </p>
				<h4 class="subheader text-center">Legal</h4>
				<p class="term-content">Proprietary Rights</p>
				<p class="term-content">All material contained in this Site is protected by law, including but not limited to, United States copyright law. Unless indicated otherwise, CareParrot is the owner of the copyright in the entire content (including images, text and look and feel attributes) of www.careparrot.com and reserves all rights in that regard. Removing or altering the copyright notice on any material on the Site is prohibited. Any commercial use of Site content is prohibited without the prior written consent of CareParrot. Unless indicated otherwise, CareParrot owns all trademarks, service marks or other logos featured on the web site. Use or misuse of these trademarks, service mark or logos is expressly prohibited and may violate federal and state law. Please be advised that CareParrot actively and aggressively enforces its intellectual property rights to the fullest extent of the law.</p>
				<h4 class="subheader text-center">Not Medical or Legal Advice</h4>
				<p class="term-content">Nothing contained, expressed or implied in the Site is intended as nor shall be construed as medical or legal advice. Inquiries about medical or legal issues, or sensitive or confidential matters should be addressed to appropriate health care or legal professionals. </p>
				<p class="term-content">Hold Harmless</p>
				<p class="term-content">You agree to indemnify and hold harmless CareParrot, its affiliates and subsidiaries, and all of their respective directors, officers, employees, representatives, proprietors, partners, shareholders, servants, principals, agents, predecessors, successors, assigns, and attorneys from and against any and all claims, proceedings, damages, injuries, liabilities, losses, costs, and expenses (including attorney's fees and litigation expenses) relating to or arising from your use of the web site and any breach by you of these Terms of Service.</p>
				<p class="term-content">Copyright and DMCA</p>
				<p class="term-content">CareParrot is committed to complying with copyright and related laws, and requires all users of the web site to comply with these laws. You may not store, post, modify, distribute, reproduce in any way, use or disseminate any material or content though the web site in any manner that constitutes an infringement of third party intellectual property rights, including rights granted by copyright law.</p>
				<p class="term-content">Reporting Violations</p>
				<p class="term-content">CareParrot respects the intellectual property of others, and expects our users to do the same. If you have a good-faith belief that any content on CareParrot violates or infringes your copyright, please complete and submit this form. We'll need you to provide us with enough information to locate the content you're concerned with, as well as an email address in case we need to contact you. Please keep in mind that we may pass along what you report on this form to the user who posted the content you're flagging.</p>
				<p class="term-content">I confirm that I have a good-faith belief that the content's use is not authorized by law, principles of fair use, the copyright owner, or the copyright owner's agent and that the information I have provided is accurate. I understand that under Section 512(f) of the Digital Millennium Copyright Act, I may be liable for any damages, including costs and attorneys’ fees, if I knowingly misrepresent or provide false information. I declare under penalty of perjury that I am authorized to act on behalf of the owner of an exclusive right that is allegedly infringed. </p>
				<p class="term-content">Arbitration Notice</p>
				<p class="term-content">You and CareParrot agree that disputes between us will be resolved by mandatory binding arbitration, and you waive any right to participate in a class action lawsuit or class wide arbitration.</p>
				<p class="term-content">Arbitration Rules</p>
				<p class="term-content">The Federal Arbitration Act governs the interpretation and enforcement of this dispute-resolution provision. Arbitration will be initiated through the American Arbitration Association ("AAA"). If the AAA is not available to arbitrate, the parties will select an alternative arbitral forum. The rules of the arbitral forum will govern all aspects of this arbitration, except to the extent those rules conflict with these Terms. The AAA Consumer Arbitration Rules governing the arbitration are available online at <a href="http://www.adr.org" target="_blank" class="btn-link">www.adr.org</a> or by calling the AAA at 1-800-778-7879. The arbitration will be conducted by a single neutral arbitrator. Any claims or disputes where the total amount sought is less than $10,000 USD may be resolved through binding non-appearance-based arbitration, at the option of the party seeking relief. For claims or disputes where the total amount sought is $10,000 USD or more, the right to a hearing will be determined by the arbitral forum's rules. Any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction.</p>
				<p class="term-content">Additional Rules for Non-appearance Arbitration</p>
				<p class="term-content">If non-appearance arbitration is elected, the arbitration will be conducted by telephone, online, written submissions, or any combination of the three; the specific manner will be chosen by the party initiating the arbitration. The arbitration will not involve any personal appearance by the parties or witnesses unless the parties mutually agree otherwise.</p>
				<p class="term-content">Authority of the Arbitrator</p>
				<p class="term-content">The arbitrator will decide the jurisdiction of the arbitrator and the rights and liabilities, if any, of you and CareParrot. The dispute will not be consolidated with any other matters or joined with any other cases or parties. The arbitrator will have the authority to grant motions dispositive of all or part of any claim or dispute. The arbitrator will have the authority to award monetary damages and to grant any non-monetary remedy or relief available to an individual under applicable law, the arbitral forum's rules, and the Terms. The arbitrator will issue a written award and statement of decision describing the essential findings and conclusions on which the award is based, including the calculation of any damages awarded. The arbitrator has the same authority to award relief on an individual basis that a judge in a court of law would have. The award of the arbitrator is final and binding upon you and CareParrot.</p>
				<p class="term-content">Waiver of Jury Trial</p>
				<p class="term-content">YOU AND CAREPARROT WAIVE ANY CONSTITUTIONAL AND STATUTORY RIGHTS TO GO TO COURT AND HAVE A TRIAL IN FRONT OF A JUDGE OR A JURY. You and CareParrot are instead electing to have claims and disputes resolved by arbitration. Arbitration procedures are typically more limited, more efficient, and less costly than rules applicable in court and are subject to very limited review by a court. In any litigation between you and CareParrot over whether to vacate or enforce an arbitration award, YOU AND CAREPARROT WAIVE ALL RIGHTS TO A JURY TRIAL, and elect instead to have the dispute be resolved by a judge.</p>
				<p class="term-content">Waiver of Class or Consolidated Actions</p>
				<p class="term-content">ALL CLAIMS AND DISPUTES WITHIN THE SCOPE OF THIS ARBITRATION AGREEMENT MUST BE ARBITRATED OR LITIGATED ON AN INDIVIDUAL BASIS AND NOT ON A CLASS BASIS. CLAIMS OF MORE THAN ONE CUSTOMER OR USER CANNOT BE ARBITRATED OR LITIGATED JOINTLY OR CONSOLIDATED WITH THOSE OF ANY OTHER CUSTOMER OR USER. If, however, this waiver of class or consolidated actions is deemed invalid or unenforceable, neither you nor we are entitled to arbitration; instead all claims and disputes will be resolved in a court as set forth in Section 18.</p>
				<p class="term-content">Confidentiality</p>
				<p class="term-content">No part of the procedures will be open to the public or the media. All evidence discovered or submitted at the hearing is confidential and may not be disclosed, except by written agreement of the parties, pursuant to court order, or unless required by law. Notwithstanding the foregoing, no party will be prevented from submitting to a court of law any information needed to enforce this arbitration agreement, to enforce an arbitration award, or to seek injunctive or equitable relief.</p>
				<p class="term-content">Right to Waive</p>
				<p class="term-content">Any rights and limitations set forth in this arbitration agreement may be waived by the party against whom the claim is asserted. Such waiver will not waive or affect any other portion of this arbitration agreement.</p>
				<p class="term-content">Opt-out</p>
				<p class="term-content">You may opt out of this arbitration agreement. If you do so, neither you nor CareParrot can force the other to arbitrate. To opt out, you must notify CareParrot in writing no later than 30 days after first becoming subject to this arbitration agreement. Your notice must include your name and address, your CareParrot username and the email address you used to set up your CareParrot account (if you have one), and an unequivocal statement that you want to opt-out of this arbitration agreement. You must send your opt-out notice to this address: CareParrot Subject: ARBITRATION OPT OUT to <a href="mailto:help@careparrot.com?subject=Hello" class="btn-link">help@careparrot.com</a> </p>
				<p class="term-content">Small Claims Court</p>
				<p class="term-content">Notwithstanding the foregoing, either you or CareParrot may bring an individual action in small claims court.</p>
				<p class="term-content">Arbitration Agreement Survival</p>
				<p class="term-content">This arbitration agreement will survive the termination of your relationship with CareParrot.</p>
				<p class="term-content">Who Can Use the Services</p>
				<p class="term-content">No one under 13 is allowed to create an account or use the Services. We may offer additional Services with additional terms that may require you to be even older to use them. So please read all terms carefully.</p>
				<p class="term-content">By using the Services, you state that:</p>
				<p class="term-content">You can form a binding contract with CareParrot;</p>
				<p class="term-content">You are not a person who is barred from receiving any of the services under the laws of the United States or any other applicable jurisdiction; and You will comply with these Terms and all applicable local, state, national, and international laws, rules, and regulations.<br/> If you are using the Services on behalf of a business or some other entity, you state that you are authorized to grant all licenses set forth in these Terms and to agree to these Terms on behalf of the business or entity. If you are using the services on behalf of an entity of the U.S. Government, you agree you are authorized to do so and agree to the Terms on behalf of the U.S. Government.</p>
				<p class="term-content">Rights We Grant You</p>
				<p class="term-content">CareParrot grants you a personal, worldwide, royalty-free, non-assignable, nonexclusive, revocable, and non-sublicensable license to access and use our services. This license is for the sole purpose of letting you use and enjoy the Service's benefits in a way that these Terms and our usage policies, such as our Community Guidelines allow. Any software that we provide you may automatically download and install upgrades, updates, or other new features. You may be able to adjust these automatic downloads through your device's settings. You may not copy, modify, distribute, sell, or lease any part of our services, nor may you reverse engineer or attempt to extract the source code of that software, unless applicable laws prohibit these restrictions or you have our written permission to do so.</p>
				<p class="term-content">Rights You Grant Us</p>
				<p class="term-content">Many of our Services let you create, upload, post, send, receive, and store content. When you do that, you retain whatever ownership rights in that content you had to begin with. But you grant us a license to use that content. How broad that license is depends on which services you use and the Settings you have selected.<br/>For all services other you grant CareParrot a worldwide, royalty-free, sub-licensable, and transferable license to host, store, use, display, reproduce, modify, adapt, edit, publish, and distribute that content. This license is for the limited purpose of operating, developing, providing, promoting, and improving the services and researching and developing new ones, also granting us a perpetual license to create derivative works from, promote, exhibit, broadcast, syndicate, publicly perform, and publicly display content submitted, or any other in any and all media or distribution methods (now known or later developed). To the extent it's necessary, you also grant CareParrot and our business partners the unrestricted, worldwide, perpetual right and license to use your name, likeness, and voice solely content that you appear in, create, upload, post, or send. This means, among other things, that you will not be entitled to any compensation from CareParrot or our business partners if your name, likeness, or voice is conveyed through our services.</p>
				<p class="term-content">While we're not required to do so, we may access, review, screen, and delete your content at any time and for any reason, including if we think your content violates these Terms. You alone though remain responsible for the content you create, upload, post, send, or store through our service. The services may contain advertisements. In consideration for CareParrot letting you access and use our services, you agree that CareParrot, its affiliates, and third-party partners may place advertising on our services. We always love to hear from our users. But if you volunteer feedback or suggestions, just know that we can use your ideas without compensating you.</p>
				<p class="term-content">The Content of Others</p>
				<p class="term-content">Much of the content on our Services is produced by users, professionals, and other third parties. Whether that content is posted publicly or sent privately, the content is the sole responsibility of the person or organization that submitted it. Although CareParrot reserves the right to review all content that appears on our services and to remove any content that violates these Terms, we do not necessarily review all of it. So we do not take responsibility for any content that others provide through the Services.</p>
				<p class="term-content">Respecting Other Rights</p>
				<p class="term-content">CareParrot respects the rights of others. And so should you. You therefore may not upload, post, send, or store content that: violates or infringes someone else's rights of publicity, privacy, copyright, trademark, or other intellectual-property right, bullies, harasses, or intimidates, defames, or spams or solicits CareParrot's users. You must also respect CareParrot's rights. These Terms do not grant you any right to: use branding, logos, designs, photographs, videos, or any other materials used in our Services, copy, archive, download, upload, distribute, syndicate, broadcast, perform, display, make available, or otherwise use any portion of the services or the content on the services except as set forth in these Terms, use the services or any content on the services for any commercial purposes without our consent.</p>
				<p class="term-content">Your Account</p>
				<p class="term-content">You are responsible for any activity that occurs in your account. So it's important that you keep your account secure. One way to do that is to select a strong password that you don't use for any other account. You agree that, in addition to exercising common sense: You will not create more than one account for yourself. You will not create another account if we have already disabled your account, unless you have our written permission to do so. You will not buy, sell, rent, or lease access to your CareParrot account. You will not share your password.You will not log in or attempt to access the services through unauthorized third-party applications or clients. If you think that someone has gained access to your account, please immediately reach out to us at <a href="mailto:help@careparrot.com?subject=Hello" class="btn-link">help@careparrot.com</a></p>
				<p class="term-content">Purchases and Payments</p>
				<p class="term-content">We may offer various virtual goods and services that you can purchase and use through the web site. You don't own these virtual goods; instead you buy a limited revocable license to use them. You'll always be shown the price for virtual goods before you complete a purchase. But CareParrot does not handle payments or payment processing for any purchases; those are handled by third-party payment providers or service providers (such as, Apple's App Store and Google's Play Store, among others). Some third-party service providers may charge you sales tax, depending on where you live. Please check the third-party service provider's relevant terms for details. Subject to any applicable additional terms and conditions, all purchases are final and non-refundable. And because our performance begins once you tap buy and we give you immediate access to your purchase, you waive any right you may have under any applicable local law to cancel your purchase once it's completed or to get a refund. BY ACCEPTING THESE TERMS, YOU AGREE THAT CAREPARROT IS NOT REQUIRED TO PROVIDE A REFUND FOR ANY REASON. Some of the virtual goods we offer are for one-time use only, while others are for repeated use. But please note that "repeated" does not mean "forever." We may change, modify, or eliminate virtual goods at any time, with or without notice. You agree that we will bear no liability to you or any third party if we do so. If we suspend or terminate your account, you will lose any virtual goods you purchased through the web site. It's your sole responsibility to manage your purchases. If you are under 18, you must obtain your parent's or guardian's consent before making any purchases.</p>
				<p class="term-content">Data Charges and Mobile Phones</p>
				<p class="term-content">You are responsible for any mobile charges that you may incur for using our web site and services, including text-messaging and data charges. If you're unsure what those charges may be, you should ask your service provider before using the web site. If you change or deactivate the mobile phone number that you used to create a CareParrot account, you must update your account information through Settings within 72 hours to prevent us from sending to someone else messages intended for you.</p>
				<p class="term-content">Modifying the Web site and Termination</p>
				<p class="term-content">We're improving our web site and creating new services all the time. That means we may add or remove features, products, or functionalities, and we may also suspend or stop the web site altogether. We may take any of these actions at any time, and when we do, we may not provide you with any notice beforehand. While we hope you remain a life long CareParrotter, you can terminate these Terms at any time and for any reason by deleting your account. CareParrot may also terminate these Terms with you at any time, for any reason, and without advanced notice. That means that we may stop providing you with any services, or impose new or additional limits on your ability to use the Web site. For example, we may deactivate your account due to prolonged inactivity, and we may reclaim your username at any time for any reason.</p>
				<p class="term-content">Disclaimers</p>
				<p class="term-content">We try to keep the Web site up and running and free of annoyances. But we make no promises that we will succeed. THE SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE" AND TO THE EXTENT PERMITTED BY APPLICABLE LAW WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. IN ADDITION, WHILE CAREPARROT ATTEMPTS TO PROVIDE A GOOD USER EXPERIENCE, WE DO NOT REPRESENT OR WARRANT THAT: (A) THE SERVICES WILL ALWAYS BE SECURE, ERROR-FREE, OR TIMELY; (B) THE SERVICES WILL ALWAYS FUNCTION WITHOUT DELAYS, DISRUPTIONS, OR IMPERFECTIONS; OR (C) THAT ANY CAREPARROT CONTENT, USER CONTENT, OR INFORMATION YOU OBTAIN ON OR THROUGH THE SERVICES WILL BE TIMELY OR ACCURATE. CAREPARROT TAKES NO RESPONSIBILITY AND ASSUMES NO LIABILITY FOR ANY CONTENT THAT YOU, ANOTHER USER, OR A THIRD PARTY CREATES, UPLOADS, POSTS, SENDS, RECEIVES, OR STORES ON OR THROUGH OUR SERVICES. YOU UNDERSTAND AND AGREE THAT YOU MAY BE EXPOSED TO CONTENT THAT MIGHT BE OFFENSIVE, ILLEGAL, MISLEADING, OR OTHERWISE INAPPROPRIATE, NONE OF WHICH CAREPARROT WILL BE RESPONSIBLE FOR.</p>
				<p class="term-content">Limitation of Liability</p>
				<p class="term-content">TO THE MAXIMUM EXTENT PERMITTED BY LAW, CAREPARROT AND OUR MANAGING MEMBERS, SHAREHOLDERS, EMPLOYEES, AFFILIATES, LICENSORS, AND SUPPLIERS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR MULTIPLE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM: (A) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICES; (B) THE CONDUCT OR CONTENT OF OTHER USERS OR THIRD PARTIES ON OR THROUGH THE SERVICES; OR (C) UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR CONTENT, EVEN IF CAREPARROT HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN NO EVENT WILL CAREPARROT'S AGGREGATE LIABILITY FOR ALL CLAIMS RELATING TO THE SERVICES EXCEED THE GREATER OF $100 USD OR THE AMOUNT YOU PAID CAREPARROT, IF ANY, IN THE LAST 12 MONTHS. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES, SO SOME OR ALL OF THE EXCLUSIONS AND LIMITATIONS IN THIS SECTION MAY NOT APPLY TO YOU.</p>
				<p class="term-content">Exclusive Venue</p>
				<p class="term-content">To the extent the parties are permitted under these Terms to initiate litigation in a court, both you and CareParrot agree that all claims and disputes arising out of or relating to the Terms or the use of the Services will be litigated exclusively in the United States District Court for South Carolina. You and CareParrot consent to the personal jurisdiction of both courts.</p>
				<p class="term-content">Severability</p>
				<p class="term-content">If any provision of these Terms is found unenforceable, then that provision will be severed from these Terms and not affect the validity and enforceability of any remaining provisions.</p>
				<p class="term-content">Final Terms</p>
				<p class="term-content">These Terms make up the entire agreement between you and CareParrot, and supersede any prior agreements. These Terms do no create or confer any third-party beneficiary rights. If we do not enforce a provision in these Terms, it will not be considered a waiver.We reserve all rights not expressly granted to you. You may not transfer any of your rights or obligations under these Terms without our consent. These Terms were written in English and to the extent the translated version of these Terms conflict with the English version, the English version will control.</p>
				<p class="term-content">Contact Us</p>
				<p class="term-content">CareParrot welcomes comments, questions, concerns, or suggestions. Please send feedback to us by visiting <a href="/" target="_blank" class="btn-link">www.careparrot.com</a></p>

				<div class="back">
					<a href="/askparrot" class="a-back">
						<img src="/assets/icons/back.png" alt="">
					</a>
				</div>
			</div>
		</div>
	</div>
</div>
@include('main.partials.templates.health-modals')
@endsection

@section('scripts')
<script type="text/javascript" src="/assets/js/about.js"></script>
<script src="/assets/js/sidebar.js"></script>
<script type="text/javascript">
	sidebar.init();
</script>
<script type="text/javascript" src="/assets/js/health.js"></script>
<script type="text/javascript">
  health.init();
</script>
@endsection
