<?php

return [
  'permission' => 'Permission for information submitted',
  'permission-desc1' => 'By submitting this application, you represent that you have permission from all of the people whose information is on the application to both submit their information to the Marketplace, and receive any communications about their eligibility and enrollment.',
  'privacy-act' => 'Privacy Act Statement – effective 10/1/2013',
  'privacy-act-desc1' => 'We are authorized to collect the information on this form and any supporting documentation, including social security numbers, under the Patient Protection and Affordable Care Act (Public Law No. 111-148), as amended by the Health Care and Education Reconciliation Act of 2010 (Public Law No. 111-152), and the Social Security Act.',
  'privacy-act-desc2' => 'We need the information provided about you and the other individuals listed on this form to determine eligibility for: (1) enrollment in a qualified health plan through the Federal Health Insurance Marketplace, (2) insurance affordability programs (such as Medicaid, CHIP, advance payment of the premium tax credits, and cost sharing reductions), and (3) certifications of exemption from the individual responsibility requirement. As part of that process, we will verify the information provided on the form, communicate with you or your authorized representative, and eventually provide the information to the health plan you select so that they can enroll any eligible individuals in a qualified health plan or insurance affordability program. We will also use the information provided as part of the ongoing operation of the Marketplace, including activities such as verifying continued eligibility for all programs, processing appeals, reporting on and managing the insurance affordability programs for eligible individuals, performing oversight and quality control activities, combatting fraud, and responding to any concerns about the security or confidentiality of the information.',
  'privacy-act-desc3' => 'While providing the requested information (including social security numbers) is voluntary, failing to provide it may delay or prevent your ability to obtain health coverage through the Marketplace, advance payment of the premium tax credits, cost sharing reductions, or an exemption from the shared responsibility payment. If you don’t have an exemption from the shared responsibility payment and you don’t maintain qualifying health coverage for three months or longer during the year, you may be subject to a penalty. If you don’t provide correct information on this form or knowingly and willfully provide false or fraudulent information, you may be subject to a penalty and other law enforcement action.',
  'privacy-act-desc4' => 'In order to verify and process applications, determine eligibility, and operate the Marketplace, we will need to share selected information that we receive outside of CMS, including to:',
  'privacy-act-li1' => 'Other federal agencies, (such as the Internal Revenue Service, Social Security Administration and Department of Homeland Security), state agencies (such as Medicaid or CHIP) or local government agencies. We may use the information you provide in computer matching programs with any of these groups to make eligibility determinations, to verify continued eligibility for enrollment in a qualified health plan or Federal benefit programs, or to process appeals of eligibility determinations. Information provided by applicants won’t be used for immigration enforcement purposes;',
  'privacy-act-li2' => 'Other verification sources including consumer reporting agencies;',
  'privacy-act-li3' => 'Employers identified on applications for eligibility determinations;',
  'privacy-act-li4' => 'Applicants/enrollees, and authorized representatives of applicants/enrollees;',
  'privacy-act-li5' => 'Agents, Brokers, and issuers of Qualified Health Plans, as applicable, who are certified by CMS who assist applicants/enrollees;',
  'privacy-act-li6' => 'CMS contractors engaged to perform a function for the Marketplace; and',
  'privacy-act-li7' => 'Anyone else as required by law or allowed under the Privacy Act System of Records Notice associated with this collection (CMS Health Insurance Exchanges System (HIX), CMS System No. 09-70-0560, as amended, 78 Federal Register, 8538, March 6, 2013, and 78 Federal Register, 32256, May 29, 2013).',
  'identity' => 'Identity Verification',
  'identity-desc1' => 'To protect your privacy, you will need to complete Identity Verification successfully before requesting higher account privileges. You are providing consent to Experian, an external identity verification provider, to access your personal information to conduct ID Verification on behalf of CMS. Below are a few items to keep in mind.',
  'identity-li1' => 'Ensure that you have entered your legal name, current home address, primary phone number, date of birth, and email address correctly. We will collect personal information only to verify your identity with Experian.',
  'identity-li2' => 'Identity Verification involves Experian using information from your consumer report profile to help confirm your identity. As a result, you may see an entry called a “soft inquiry” on your Experian consumer report. Soft inquiries are visible only to you, will never be presented to third parties, and do not affect your credit score. The soft inquiry will be titled “CMS Proofing Services” and will be removed from your Experian consumer report after 25 months.',
  'identity-li3' => 'You may need to have access to your personal and consumer report information, as the Experian application will pose questions to you, based on data in their files.',
  'identity-desc2' => 'This statement provides the notice required by the Privacy Act of 1974 (5 U.S.C. § 552a(e)(3)). You can learn more about how we handle your information at:',

];
