<?php

return [
  'permission' => 'Permission pour information soumis',
  'permission-desc1' => "En soumettant cette application, vous représentez que vous avez la permission de toutes les personnes dont l'information est sur l'application à toutes les deux soumettent leur information au marché, et reçoivent toutes les communications au sujet de leur acceptabilité et inscription.",
  'privacy-act' => "Rapport de Loi d'intimité - 10/1/2013 efficace",
  'privacy-act-desc1' => "Nous sommes autorisés à rassembler l'information sur cette forme et n'importe quelle documentation de soutien, y compris des nombres de sécurité sociale, sous la protection patiente et la Loi accessible de soin (No. public de loi. 111-148), comme modifié par l'acte de réconciliation de santé et d'éducation de 2010 (No. public de loi. 111-152), et la Loi de sécurité sociale.",
  'privacy-act-desc2' => "Nous avons besoin des informations fournies au sujet de toi et des autres individus énumérés sur cette forme pour déterminer l'acceptabilité pour : (1) inscription dans un plan qualifié de santé par le marché fédéral d'assurance médicale maladie, (2) programmes d'accessibilité d'assurance (tels que Medicaid, MORCEAU, paiement anticipé des crédits de taxe sur primes, et réductions de partage des coûts), et (3) certifications d'exemption de la condition individuelle de responsabilité. En tant qu'élément de ce processus, nous vérifierons les informations fournies sur la forme, communiquons avec toi ou votre représentant autorisé, et fournissons par la suite les informations au plan de santé vous choisi de sorte qu'ils puissent s'inscrire tous les individus éligibles dans un programme qualifié d'accessibilité de plan ou d'assurance de santé. Nous emploierons également les informations fournies en tant qu'élément de l'opération continue du marché, y compris des activités telles que vérifier l'acceptabilité continue pour tous les programmes, traiter des appels, signaler et contrôler les programmes d'accessibilité d'assurance pour les individus éligibles, exécutant des activités d'inadvertance et de contrôle de qualité, la fraude combattante, et répondre à tous les soucis concernant la sécurité ou la confidentialité d'information.",
  'privacy-act-desc3' => "Tandis que fournir les informations demandées (nombres y compris de sécurité sociale) est volontaire, ne les fournit pas peut retarder ou empêcher votre capacité d'obtenir l'assurance de santé par le marché, le paiement anticipé des crédits de taxe sur primes, les réductions de partage des coûts, ou une exemption du paiement partagé de responsabilité. Si vous n'avez pas une exemption du paiement partagé de responsabilité et vous ne maintenez pas l'assurance de qualification de santé pendant trois mois ou plus long pendant l'année, vous pouvez être sujette à une pénalité. Si vous ne fournissez pas des informations correctes sur cette forme ou ne fournissez pas sciemment et obstinément des informations fausses ou frauduleuses, vous pouvez être sujette à une pénalité et à toute autre action d'application de loi.",
  'privacy-act-desc4' => "Afin de vérifier et des applications de processus, déterminer l'acceptabilité, et actionner le marché, nous devrons partager l'information choisie que nous recevons l'extérieur du CMS, incluant à :",
  'privacy-act-li1' => "D'autres agences fédérales, (comme le service de recettes, l'administration de sécurité sociale et le département de la sécurité de patrie), agences d'état (telles que Medicaid ou MORCEAU) ou organismes gouvernementaux locaux. Nous pouvons employer l'information que vous fournissez dans des programmes de croisement de fichiers en quelconque d'entre ces groupes pour faire des déterminations d'acceptabilité, pour vérifier l'acceptabilité continue pour l'inscription dans un plan qualifié de santé ou des programmes sociaux fédéraux, ou pour traiter des appels des déterminations d'acceptabilité. L'information a fourni par des demandeurs ne sera pas employée pour l'application d'immigration ;",
  'privacy-act-li2' => "D'autres sources de vérification comprenant des agences de reportage du consommateur ;",
  'privacy-act-li3' => "Employeurs identifiés sur des demandes de déterminations d'acceptabilité ;",
  'privacy-act-li4' => 'Demandeurs/enrôlés, et représentants autorisés des demandeurs/des enrôlés ;',
  'privacy-act-li5' => 'Les agents, sponsorise, et des émetteurs des plans qualifiés de santé, comme applicable, qui sont certifiés par le CMS qui aident des demandeurs/enrôlés ;',
  'privacy-act-li6' => 'Les entrepreneurs de CMS se sont engagés pour exécuter une fonction pour le marché ; et',
  'privacy-act-li7' => "N'importe qui autrement selon les exigences de la loi ou permis sous le système de Loi d'intimité de la notification de disques s'est associé à cette collection (système des échanges d'assurance médicale maladie de CMS (HIX), No. de système de CMS. 09-70-0560, comme modifié, 78 registre fédéral, 8538, 6 mars 2013, et 78 registre fédéral, 32256, 29 mai 2013).",
  'identity' => "Vérification d'identité",
  'identity-desc1' => "Pour protéger votre intimité, vous devrez accomplir la vérification d'identité avec succès avant de demander des privilèges plus élevés de compte. Vous fournissez le consentement à Experian, un fournisseur externe de vérification d'identité, pour accéder à votre information personnelle pour conduire la vérification d'identification au nom du CMS. Au-dessous de sont quelques articles à maintenir dans l'esprit.",
  'identity-li1' => "Assurez-vous que vous avez écrit votre nom légal, adresse à la maison courante, nombre de téléphone primaire, date de naissance, et email address correctement. Nous rassemblerons l'information personnelle pour vérifier seulement votre identité avec Experian.",
  'identity-li2' => "La vérification d'identité implique Experian en utilisant l'information de votre profil de rapport du consommateur pour aider à confirmer votre identité. En conséquence, vous pouvez voir une entrée appelée « une enquête douce » sur votre rapport du consommateur d'Experian. Les enquêtes douces sont évidentes seulement à toi, ne seront jamais présentées aux tiers, et n'affectent pas vos points de crédit. L'enquête douce sera intitulée « des services d'imperméabilisation de CMS » et enlevée de votre rapport du consommateur d'Experian après 25 mois.",
  'identity-li3' => "Vous pouvez devoir avoir accès à votre information personnelle et du consommateur de rapport, car l'application d'Experian posera des questions à toi, basée sur des données dans leurs dossiers.",
  'identity-desc2' => "Ce rapport fournit la notification exigée par la Loi d'intimité de 1974 (5 U.S.C. § 552a (e) (3)). Vous pouvez apprendre plus au sujet derrière de la façon dont nous manipulons votre information :",

];
