<?php

return [
  'permission' => 'El permiso para la información sometió',
  'permission-desc1' => 'sometiendo este uso, usted representa que usted tiene permiso de toda la gente que información esté en el uso a ambas someta su información al mercado, y reciba cualquier comunicación sobre su elegibilidad e inscripción.',
  'privacy-act' => 'Declaración del acto de la aislamiento - 10/1/2013 eficaz',
  'privacy-act-desc1' => 'nos autorizan a recoger la información sobre esta forma y cualquier documentación de soporte, incluyendo números de Seguridad Social, bajo la protección paciente y acto comprable del cuidado (No. público de derecho. 111-148), según la enmienda prevista por el acto de la reconciliación del cuidado médico y de la educación de 2010 (No. público de derecho. 111-152), y el acto de la Seguridad Social.',
  'privacy-act-desc2' => 'Necesitamos a la información proporcionada sobre usted y a los otros individuos enumerados en esta forma para determinar la elegibilidad para: (1) inscripción en un plan cualificado de la salud a través del mercado federal del seguro médico, (2) programas del affordability del seguro (tales como Medicaid, VIRUTA, pago anticipado de los créditos de impuesto superior, y reducciones del reparto de gastos), y (3) certificaciones de la exención del requisito individual de la responsabilidad. Como parte de ese proceso, verificaremos la información proporcionada en la forma, nos comunicamos con usted o su representante autorizado, y proporcionamos eventual la información al plan de la salud usted selecto de modo que puedan alistar a cualquier individuo elegible en un programa cualificado del affordability del plan o del seguro de la salud. También utilizaremos la información proporcionada como parte de la operación en curso del mercado, incluyendo actividades tales como verificar la elegibilidad continuada para todos los programas, proceso de súplicas, divulgación encendido y manejo de los programas del affordability del seguro para los individuos elegibles, realizando actividades del descuido y del control de calidad, fraude que combate, y responder a cualquier preocupación por la seguridad o el secreto de la información.',
  'privacy-act-desc3' => 'Mientras que el abastecimiento de la información solicitada (números de Seguridad Social incluyendo) es voluntario, el no poder proporcionarla puede retrasar o prevenir su capacidad de obtener cobertura de la salud a través del mercado, el pago anticipado de los créditos de impuesto superior, reducciones del reparto de gastos, o una exención del pago compartido de la responsabilidad. Si usted no tiene una exención del pago compartido de la responsabilidad y usted no mantiene la cobertura calificativa de la salud por tres meses o más largo durante el año, usted puede estar conforme a una pena. Si usted no proporciona la información correcta en esta forma o no proporciona con conocimiento y voluntarioso la información falsa o fraudulenta, usted puede estar conforme a la pena y a la otra acción de la aplicación de ley.',
  'privacy-act-desc4' => 'Para verificar y los usos de proceso, determinar elegibilidad, y funcionar el mercado, necesitaremos compartir la información seleccionada que recibimos el exterior del CMS, incluyendo a:',
  'privacy-act-li1' => 'Otras agencias federales, (por ejemplo el servicio de renta pública, la administración de Seguridad Social y el departamento de la seguridad de la patria), agencias del estado (tales como Medicaid o VIRUTA) o agencias de estatal local. Podemos utilizar la información que usted proporciona en programas el emparejar de computadora de ninguno de estos grupos para hacer determinaciones de la elegibilidad, para verificar la elegibilidad continuada para la inscripción en un plan cualificado de la salud o programas de ventaja federales, o para procesar súplicas de las determinaciones de la elegibilidad. La información proporcionada por los aspirantes no será utilizada para los propósitos de aplicación de la inmigración;',
  'privacy-act-li2' => 'Otras fuentes de la verificación incluyendo las agencias de divulgación de consumidor;',
  'privacy-act-li3' => 'Patrones identificados en los usos para las determinaciones de la elegibilidad;',
  'privacy-act-li4' => 'Aspirantes/enrollees, y representantes autorizados de aspirantes/de enrollees;',
  'privacy-act-li5' => 'Agentes, corredores, y emisores de los planes cualificados de la salud, como aplicables, que son certificados por el CMS que asiste a aspirantes/a enrollees;',
  'privacy-act-li6' => 'Los contratistas del CMS engancharon para realizar una función para el mercado; y',
  'privacy-act-li7' => 'Cualquier persona según los requisitos de ley o permitida bajo sistema del acto de la aislamiento del aviso de los expedientes se asoció a esta colección (sistema de cambios del seguro médico del CMS (HIX), No. del sistema del CMS. 09-70-0560, según la enmienda prevista, 78 registro federal, 8538, el 6 de marzo de 2013, y 78 registro federal, 32256, 29 de mayo de 2013).',
  'identity' => 'Verificación de la identidad',
  'identity-desc1' => 'para proteger su aislamiento, usted necesitará terminar la verificación de la identidad con éxito antes de solicitar privilegios más altos de la cuenta. Usted está proporcionando consentimiento a Experian, un abastecedor externo de la verificación de la identidad, para tener acceso a su información personal para conducir la verificación de la identificación a nombre del CMS. Debajo están algunos artículos a tener presente.',
  'identity-li1' => 'Asegúrese de que usted haya incorporado su nombre legal, dirección casera actual, número de teléfono primario, fecha de nacimiento, y email address correctamente. Recogeremos la información personal para verificar solamente su identidad con Experian.',
  'identity-li2' => 'La verificación de la identidad implica Experian usando la información de su perfil del informe del consumidor para ayudar a confirmar su identidad. Consecuentemente, usted puede ver una entrada llamada una “investigación suave” en su informe del consumidor de Experian. Las investigaciones suaves son visibles solamente a usted, nunca serán presentadas a los terceros, y no afectan su cuenta del crédito. La investigación suave será titulada “los servicios del Proofing del CMS” y quitada de su informe del consumidor de Experian después de 25 meses.',
  'identity-li3' => 'Usted puede necesitar tener acceso a su información personal y del consumidor del informe, como el uso de Experian planteará preguntas a usted, basada en datos en sus archivos.',
  'identity-desc2' => 'Esta declaración proporciona el aviso requerido por el acto de la aislamiento de 1974 (5 U.S.C. § 552a (e) (3)).',

];
