<?php namespace Categories;

use Illuminate\Database\Seeder;
use App\Models\Category;

class SigSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dosages = [
            'None',
            'Apply',
            'Apply Sparingly',
            '0.1',
            '0.25',
            '0.5',
            '1',
            '2',
            '3',
            '4',
            '1-2',
            '2-3',
            '2-4',
            '3-4',
            '5',
            '5-10',
            '6',
            '7',
            '8',
            '9',
            '10',
            '10-15',
            '15',
            '20',
            '10-20',
            '25',
            '30',
            '40',
            '50',
            '60',
            '70',
            '75',
            '80',
            '90',
            '100',
            '125',
            '150',
            '175',
            '200',
            '225',
            '250',
            '275',
            '300',
            '400',
            '500',
            '600',
            '750',
            '875',
            '1000',
        ];

        $units = [
            'None',
            'milligram (s)',
            'milliliter (s)',
            'gram (s)',
            'unit (s)',
            'international unit (s)',
            'microgram (s)',
            'each',
            'inch (es)',
            'milliequivalent (s)',
            'drop (s)',
            'applicatorful',
            'scoop (s)',
            'day (s)',
            'hour (s)',
            'minute (s)',
            'suppository (ies)',
            'gum',
            'patch',
            'lozenge (s)',
            'million unit (s)',
            'centimeter (s)',
            'millimole (s)',
            'cap (s)',
            'liter (s)',
            'tab (s)',
            'puff (s)',
            'spray (s)',
            'g/kg',
            'international units / kg',
            'mcg/kg',
            'mcg/m2',
            'mEq/kg',
            'mg/kg',
            'mg/kg/day',
            'mg/m2',
            'mg/m2/day',
            'mL/kg',
            'mmol/kg',
            'units/kg',
            'units/kg/day',
            'units/m2',
            'mg/24h',
            'week (s)',
            'dose (s)',
            'square centimeter',
            'inhalation',
            'packet (s)',
            'insert',
            'kit',
            'gram/m2',
            'month (s)',
            'international units/m2',
            'mL/m2',
            'application',
            'nanogram (s)',
            'ng/kg',
            'parts per million',
            'protein nitrogen unit',
            'megabecquerel (s) (edited)',
            'millicurie',
            'microcurie',
            'mg/hr',
            'mcg/hr',
            'mcg/hr',
            'pump (s)',
            'mcg/day'
        ];

        $routes = [
            'None',
            'implant',
            'inhalation',
            'compounding',
            'injectable',
            'intra-articular',
            'intrabiliary',
            'intradermal',
            'intralymphatic',
            'intramuscular',
            'intraocular',
            'intraperitoneal',
            'intrathecal',
            'intratracheal',
            'intrauteral',
            'intravenous',
            'irrigation',
            'mucous membrane',
            'nasal',
            'ophthalmic',
            'oral',
            'oral and injectable',
            'oral transmucosal',
            'otic',
            'rectal',
            'subcutaneous',
            'sublingual',
            'tropical',
            'transdermal',
            'transurethral',
            'vaginal',
            'buccal',
            'intravitreal',
            'intrapleural',
            'intravesical',
            'oral and rectal',
            'oral and topical',
            'enteral',
            'percutaneous',
            'spinal',
            'parenteral'
        ];

        $frequencies = [
            'None',
            '3 times a day',
            '3 times a week',
            '4 times a day',
            '5 times a day',
            'every 18 hours',
            'every 36 hours',
            'every 48 hours',
            'every 72 hours',
            'every 7 days',
            'every other day',
            'once a day',
            'once a month',
            'once a week',
            '2 times a day',
            '2 times a week',
            'every 15 minutes',
            'every hour',
            '10 times a day',
            '12 times a day',
            '16 times a day',
            '6 times a day',
            '7 times a day',
            '8 times a day',
            'every 16 hours',
            'every 2 weeks',
            'every 30 minutes',
            'every 40 hours',
            'yearly',
            '9 times a day',
            'every 3 weeks',
            'every 5 days',
            'every 60 hours',
            'every 6 weeks',
            '3 times a day (after meals)',
            '3 times a day (before meals)',
            '3 times a day (after meals and at bedtime)',
            '4 times a day (after meals and at bedtime)',
            '4 times a day (before meals and at bedtime)',
            '4 times a day (with meals and at bedtime)',
            'every 10 minutes',
            'every 12 hours',
            'every 2 hours',
            'every 24 hours',
            'every 3 days',
            'every 3 hours',
            'every 4 days',
            'every 4 hours',
            'every 5 minutes',
            'every 6 hours',
            'every 8 hours',
            'every 96 hours',
            'once',
            'once a day (at bedtime)',
            'once a day (in the morning)',
            'once a day (before a meal)',
            '4 to 6 times a day',
            'every 1 to 2 hours',
            'every 3 months',
            'every 30 to 60 minutes',
            '5 times a week',
            '2 times a day (with meals)',
            '2 to 4 times a day',
            '1 to 2 times a day',
            'every 6 to 15 minutes',
            'every 10 to 15 minutes',
            'every 4 to 6 hours',
            'every 6 to 8 hours',
            '3 to 4 times a day',
            '1 to 4 times a day',
            'twice',
            'every 5 to 8 months',
            '4 times a week',
            '6 times a week',
            'every 10 to 30 minutes',
            'every 2 to 3 hours',
            'every 2 to 3 minutes',
            'every 2 to 4 hours',
            'every 25 to 60 minutes',
            'every 25 minutes',
            'every 2 to 5 minutes',
            'every 2 minutes',
            'every 3 to 4 hours',
            'every 3 to 5 hours',
            'every 3 to 6 hours',
            'every 4 weeks',
            'every 5 to 15 minutes',
            'every 6 months',
            'every 8 to 12 hours',
            'every other week',
            'every 20 minutes',
            'every 5 hours',
            'every 5 to 10 minutes',
            '2 times a day (after meals)',
            'once a day (after a meal)',
            'every other day (at bedtime)',
            'once a day (in the evening)',
            'every 3 to 4 weeks',
            '3 to 4 times a week',
            '1 to 3 times a day',
            'every 4 hours while awake',
            'every minute',
            '3 times',
            'every 4 months',
            'every 90 minutes',
            'every 10 hours',
            'every 4 hours (5 times/day)',
            'Monday through Friday',
            'Monday, Wednesday and Friday',
            'in the morning and at bedtime',
            '2 times a day (before meals)',
            'now',
            'every 4 to 8 hours',
            'every 3 to 6 months',
            'every 3 to 4 days',
            '2 times a day (3 days a week)',
            'every 3 minutes',
            'every 8 weeks',
            'every 2 months',
            'every 10 weeks',
            '2 times a month',
            'every 4 minutes',
            'Tuesday, Thursday, Saturday',
            'every 6 days',
            'every 14 weeks',
            'every 10 days',
        ];

        $directions = [
            'None',
            'as needed',
            'before meals',
            'after meals',
            'with meals',
            'before every meal',
            'after every meal',
            'in the morning',
            'in the afternoon',
            'in the evening',
            'at bedtime',
            'x1 week',
            'x2 weeks',
            'x3 weeks',
            'x4 weeks',
            'x6 weeks',
            'x8 weeks',
            'alternate nostrils',
            'swish/spit',
            'swish/swallow',
        ];

        $durations = [
            'None',
            'x2 doses',
            'x3 doses',
            'x4 doses',
            'x1 day',
            'x2 day',
            'x3 days',
            'x7 days',
            'x10 days',
            'x1 week',
            'x2 weeks',
            'x3 weeks',
            'x4 weeks',
            'x6 weeks',
            'x8 weeks',
            'x12 weeks',
            'x1 month',
            'x2 months',
            'x3 months',
            'x6 months'
        ];

        $sig = [
            'dosages' => $dosages,
            'units' => $units,
            'routes' => $routes,
            'frequencies' => $frequencies,
            'directions' => $directions,
            'durations' => $durations,
        ];
        
        $s = 10;
        $i = 0;
        foreach ($sig as $key => $value) {
            $startCode = str_pad( (string) $s, 5, '0', STR_PAD_LEFT);
            foreach ($value as $val) {
                $i++;
                $code = $startCode.str_pad($i, 5, '0', STR_PAD_LEFT);
                Category::create([
                    'category_code' => $code,
                    'category_desc' => 'SIG ' . ucfirst($key),
                    'title' => $val,
                ]);
            }
            $i = 0;
            $s++;
        }
    }
}
